FROM node:10-alpine3.10 as builder
WORKDIR /client/app
COPY package*.json ./
RUN npm install --silent
COPY . ./
RUN npm run build

FROM nginx:latest
COPY --from=builder /client/app/build /usr/share/nginx/html
COPY ./docker/nginx/default.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
EXPOSE 3000
CMD ["nginx", "-g", "daemon off;"]