apiVersion: apps/v1
kind: StatefulSet
metadata:
 name: customer-database
spec:
  serviceName: customer-database
  selector:
    matchLabels:
      database: customer
  template:
    metadata:
      labels:
        database: customer
        system: database
    spec:
      terminationGracePeriodSeconds: 60
      securityContext:
        fsGroup: 10001
      containers:
      - name: customer-database
        image: mcr.microsoft.com/mssql/server:2019-latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 1433
        resources:
          limits:
            memory: "2Gi"
            cpu: "250m"
        env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: SA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: environment-secrets
              key: customer-database-sa-password
        volumeMounts:
        - name: customer-database-data
          mountPath: /var/opt/mssql
      volumes:
      - name: customer-database-data
        persistentVolumeClaim:
          claimName: customer-database-data