apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: admin-client-data
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi

---

apiVersion: v1
kind: Service
metadata:
  name: admin-client
spec:
  type: LoadBalancer
  ports:
  - port: 50400
    targetPort: 80
  selector:
    web-client: admin-client

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-client
spec:
  selector:
    matchLabels:
      web-client: admin-client
  template:
    metadata:
      labels:
        web-client: admin-client
        system: client
    spec:
      containers:
      - name: admin-client
        image: zlatkorusev/microservices-architecture-admin-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "250Mi"
            cpu: "250m"
        env:
        - name: ASPNETCORE_ENVIRONMENT
          valueFrom:
            secretKeyRef:
              name: environment-secrets
              key: aspnetcore-environment
        - name: AppSettings__Secret
          valueFrom:
            secretKeyRef:
              name: environment-secrets
              key: security-token-secret
        - name: AppSettings__Issuer
          valueFrom:
            secretKeyRef:
              name: environment-secrets
              key: security-token-issuer
        - name: AppSettings__Audience
          valueFrom:
            secretKeyRef:
              name: environment-secrets
              key: security-token-audience
        - name: AppSettings__Expiration
          valueFrom:
            secretKeyRef:
              name: environment-secrets
              key: security-token-expiration
        - name: ServiceEndpoints__Statistics
          valueFrom:
            configMapKeyRef:
              name: environment-settings
              key: service-endpoints-statistics
        - name: ServiceEndpoints__Customers
          valueFrom:
            configMapKeyRef:
              name: environment-settings
              key:  service-endpoints-customers
        - name: ServiceEndpoints__Identity
          valueFrom:
            configMapKeyRef:
              name: environment-settings
              key:  service-endpoints-identity
        - name: Monitoring_Address
          valueFrom:
            configMapKeyRef:
              name: environment-settings
              key:  monitoring-settings-address
        - name: MassTransitCredentials__HostName
          valueFrom:
            configMapKeyRef:
              name: environment-settings
              key: massTransit-credentials-hostName
        - name: MassTransitCredentials__User
          valueFrom:
            configMapKeyRef:
              name: environment-settings
              key: massTransit-credentials-user
        - name: MassTransitCredentials__Password
          valueFrom:
            secretKeyRef:
              name: environment-secrets
              key: massTransit-credentials-password
        volumeMounts:
        - name: admin-client-data
          mountPath: /root/.aspnet/DataProtection-Keys
      volumes:
      - name: admin-client-data
        persistentVolumeClaim:
          claimName: admin-client-data
