apiVersion: v1
kind: Service
metadata:
  name: watchdog-client
spec:
  type: LoadBalancer
  ports:
  - port: 5013
    targetPort: 80
  selector:
    web-client: watchdog-client

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: watchdog-client
spec:
  selector:
    matchLabels:
      web-client: watchdog-client
  template:
    metadata:
      labels:
        web-client: watchdog-client
        system: client
    spec:
      containers:
      - name: watchdog-client
        image: zlatkorusev/microservices-architecture-monitoring-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "128Mi"
            cpu: "250m"
        env:
        - name: HealthChecks-UI__HealthChecks__0__Name
          value: Identity Service
        - name: HealthChecks-UI__HealthChecks__0__Uri
          valueFrom:
            configMapKeyRef:
              name: environment-settings
              key: watchdog-identity-health
        - name: HealthChecks-UI__HealthChecks__1__Name
          value: Customers Service
        - name: HealthChecks-UI__HealthChecks__1__Uri
          valueFrom:
            configMapKeyRef:
              name: environment-settings
              key: watchdog-customers-health
        - name: HealthChecks-UI__HealthChecks__2__Name
          value: Statistics Service
        - name: HealthChecks-UI__HealthChecks__2__Uri
          valueFrom:
            configMapKeyRef:
              name: environment-settings
              key: watchdog-statistics-health
        - name: HealthChecks-UI__HealthChecks__3__Name
          value: Notifications Service
        - name: HealthChecks-UI__HealthChecks__3__Uri
          valueFrom:
            configMapKeyRef:
              name: environment-settings
              key: watchdog-notifications-health
        - name: HealthChecks-UI__HealthChecks__4__Name
          value: Admin Service
        - name: HealthChecks-UI__HealthChecks__4__Uri
          valueFrom:
            configMapKeyRef:
              name: environment-settings
              key: watchdog-admin-health
