apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: customer-service-data
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi

---

apiVersion: v1
kind: Service
metadata:
  name: customer-service
spec:
  type: LoadBalancer
  ports:
  - port: 5003
    targetPort: 80
  selector:
    web-service: customer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-service
spec:
  selector:
    matchLabels:
      web-service: customer
  template:
    metadata:
      labels:
        web-service: customer
        system: server
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                web-service: customer
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: customer-service
        image: zlatkorusev/microservices-architecture-customers-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "250Mi"
            cpu: "250m"
        env:
        - name: ASPNETCORE_ENVIRONMENT
          valueFrom:
            secretKeyRef:
              name: environment-secrets
              key: aspnetcore-environment
        - name: AppSettings__Secret
          valueFrom:
            secretKeyRef:
              name: environment-secrets
              key: security-token-secret
        - name: AppSettings__Issuer
          valueFrom:
            secretKeyRef:
              name: environment-secrets
              key: security-token-issuer
        - name: AppSettings__Audience
          valueFrom:
            secretKeyRef:
              name: environment-secrets
              key: security-token-audience
        - name: AppSettings__Expiration
          valueFrom:
            secretKeyRef:
              name: environment-secrets
              key: security-token-expiration
        - name: ConnectionStrings__DefaultConnection
          valueFrom:
            secretKeyRef:
              name: environment-secrets
              key: customer-service-connection-string
        - name: AdminCredentials__Email
          valueFrom:
            secretKeyRef:
              name: environment-secrets
              key: admin-credentials-email
        - name: AdminCredentials__Password
          valueFrom:
            secretKeyRef:
              name: environment-secrets
              key: admin-credentials-password
        - name: MassTransitCredentials__HostName
          valueFrom:
            configMapKeyRef:
              name: environment-settings
              key: massTransit-credentials-hostName
        - name: MassTransitCredentials__User
          valueFrom:
            configMapKeyRef:
              name: environment-settings
              key: massTransit-credentials-user
        - name: MassTransitCredentials__Password
          valueFrom:
            secretKeyRef:
              name: environment-secrets
              key: massTransit-credentials-password
        volumeMounts:
        - name: customer-service-data
          mountPath: /root/.aspnet/DataProtection-Keys
      volumes:
      - name: customer-service-data
        persistentVolumeClaim:
          claimName: customer-database-data
          #claimName: identity-database-data #local env pvc