apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: customer-gateway-service-data
spec:
  accessModes:
  - ReadWriteOnce
  - ReadOnlyMany
  resources:
    requests:
      storage: 10Mi

---

apiVersion: v1
kind: Service
metadata:
  name: customer-gateway-service
spec:
  type: LoadBalancer
  ports:
  - port: 5007
    targetPort: 80
  selector:
    web-service: customer-gateway

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-gateway-service
spec:
  selector:
    matchLabels:
      web-service: customer-gateway
  template:
    metadata:
      labels:
        web-service: customer-gateway
        system: server
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                web-service: customer-gateway
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: customer-gateway-service
        image: zlatkorusev/microservices-architecture-customers-gateway-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "128Mi"
            cpu: "250m"
        env:
        - name: ASPNETCORE_ENVIRONMENT
          valueFrom:
            secretKeyRef:
              name: environment-secrets
              key: aspnetcore-environment
        - name: AppSettings__Secret
          valueFrom:
            secretKeyRef:
              name: environment-secrets
              key: security-token-secret
        - name: AppSettings__Issuer
          valueFrom:
            secretKeyRef:
              name: environment-secrets
              key: security-token-issuer
        - name: AppSettings__Audience
          valueFrom:
            secretKeyRef:
              name: environment-secrets
              key: security-token-audience
        - name: AppSettings__Expiration
          valueFrom:
            secretKeyRef:
              name: environment-secrets
              key: security-token-expiration
        - name: ServiceEndpoints__Statistics
          valueFrom:
            configMapKeyRef:
              name: environment-settings
              key: service-endpoints-statistics
        - name: ServiceEndpoints__Customers
          valueFrom:
            configMapKeyRef:
              name: environment-settings
              key:  service-endpoints-customers
        volumeMounts:
        - name: customer-gateway-service-data
          mountPath: /root/.aspnet/DataProtection-Keys
      volumes:
      - name: customer-gateway-service-data
        persistentVolumeClaim:
          claimName: customer-gateway-service-data