apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: notifications-service-data
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi

---

apiVersion: v1
kind: Service
metadata:
  name: notifications-service
spec:
  type: LoadBalancer
  ports:
  - port: 5011
    targetPort: 80
  selector:
    web-service: notifications

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: notifications-service
spec:
  selector:
    matchLabels:
      web-service: notifications
  template:
    metadata:
      labels:
        web-service: notifications
        system: server
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                web-service: notifications
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: notifications-service
        image: zlatkorusev/microservices-architecture-notifications-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "128Mi"
            cpu: "250m"
        env:
        - name: ASPNETCORE_ENVIRONMENT
          valueFrom:
            secretKeyRef:
              name: environment-secrets
              key: aspnetcore-environment
        - name: AppSettings__Secret
          valueFrom:
            secretKeyRef:
              name: environment-secrets
              key: security-token-secret
        - name: AppSettings__Issuer
          valueFrom:
            secretKeyRef:
              name: environment-secrets
              key: security-token-issuer
        - name: AppSettings__Audience
          valueFrom:
            secretKeyRef:
              name: environment-secrets
              key: security-token-audience
        - name: AppSettings__Expiration
          valueFrom:
            secretKeyRef:
              name: environment-secrets
              key: security-token-expiration
        - name: ClientSettings__Address
          valueFrom:
            configMapKeyRef:
              name: environment-settings
              key: client-settings-address
        - name: MassTransitCredentials__HostName
          valueFrom:
            configMapKeyRef:
              name: environment-settings
              key: massTransit-credentials-hostName
        - name: MassTransitCredentials__User
          valueFrom:
            configMapKeyRef:
              name: environment-settings
              key: massTransit-credentials-user
        - name: MassTransitCredentials__Password
          valueFrom:
            secretKeyRef:
              name: environment-secrets
              key: massTransit-credentials-password
        volumeMounts:
        - name: notifications-service-data
          mountPath: /root/.aspnet/DataProtection-Keys
      volumes:
      - name: notifications-service-data
        persistentVolumeClaim:
          claimName: notifications-service-data
