apiVersion: v1
kind: ConfigMap
metadata:
 name: environment-settings
data:
  event-bus-host: event-bus
  event-bus-user: rabbitmquser
  massTransit-credentials-hostName: event-bus
  massTransit-credentials-user: rabbitmquser
  client-settings-address: http://localhost:3000