apiVersion: v1
kind: Secret
metadata:
  name: environment-secrets
data:
  aspnetcore-environment: RGV2ZWxvcG1lbnQ=
  identity-database-sa-password: NjUxNjUxYzFGMDI4IUA=
  customer-database-sa-password: NjUxNjUxYzFGMDI4IUA=
  statistics-database-sa-password: NjUxNjUxYzFGMDI4IUA=
  security-token-secret: Y2JlOTZhNzMtNGI0MS00ZWEyLWE5NjAtMTIxMzU3Mzg0Mzg1
  security-token-issuer: aHR0cDovL2lkZW50aXR5Ojgw
  security-token-audience: aHR0cDovL2lkZW50aXR5Ojgw
  security-token-expiration: NQ==
  admin-credentials-email: YWRtaW5AYWRtaW4uYmc=
  admin-credentials-password: YWRtaW4xMw==
  identity-service-connection-string: U2VydmVyPWlkZW50aXR5LWRhdGFiYXNlO0RhdGFiYXNlPVN0b3JlQXBwSWRlbnRpdHlEQjtVc2VyIElkPXNhO1Bhc3N3b3JkPTY1MTY1MWMxRjAyOCFAO011bHRpcGxlQWN0aXZlUmVzdWx0U2V0cz10cnVl