apiVersion: v1
kind: ConfigMap
metadata:
 name: environment-settings
data:
  event-bus-host: event-bus
  event-bus-user: rabbitmquser
  massTransit-credentials-hostName: event-bus
  massTransit-credentials-user: rabbitmquser
  client-settings-address: http://localhost
  service-endpoints-statistics: http://statistics-service:5005
  service-endpoints-customers: http://customer-service:5003