apiVersion: v1
kind: ConfigMap
metadata:
 name: environment-settings
data:
  event-bus-host: event-bus
  event-bus-user: rabbitmquser
  massTransit-credentials-hostName: event-bus
  massTransit-credentials-user: rabbitmquser
  client-settings-address: http://localhost
  monitoring-settings-address: http://localhost:5013/healthchecks-ui
  service-endpoints-statistics: http://statistics-service:5005
  service-endpoints-customers: http://customer-service:5003
  service-endpoints-identity: http://identity-service:5001
  watchdog-identity-health: http://identity-service:5001/health
  watchdog-customers-health: http://customer-service:5003/health
  watchdog-statistics-health: http://statistics-service:5005/health
  watchdog-notifications-health: http://notifications-service:5011/health
  watchdog-admin-health: http://admin-client:50400/health

---

apiVersion: v1
kind: Secret
metadata:
  name: environment-secrets
data:
  aspnetcore-environment: RGV2ZWxvcG1lbnQ=
  redis-database-sa-password: NjUxNjUxYzFGMDI4IUA=
  identity-database-sa-password: NjUxNjUxYzFGMDI4IUA=
  customer-database-sa-password: NjUxNjUxYzFGMDI4IUA=
  statistics-database-sa-password: NjUxNjUxYzFGMDI4IUA=
  order-database-sa-password: NjUxNjUxYzFGMDI4IUA=
  security-token-secret: Y2JlOTZhNzMtNGI0MS00ZWEyLWE5NjAtMTIxMzU3Mzg0Mzg1
  security-token-issuer: aHR0cDovL2lkZW50aXR5Ojgw
  security-token-audience: aHR0cDovL2lkZW50aXR5Ojgw
  security-token-expiration: NQ==
  admin-credentials-email: YWRtaW5AYWRtaW4uYmc=
  admin-credentials-password: YWRtaW4xMw==
  identity-service-connection-string: U2VydmVyPWlkZW50aXR5LWRhdGFiYXNlO0RhdGFiYXNlPVN0b3JlQXBwSWRlbnRpdHlEQjtVc2VyIElkPXNhO1Bhc3N3b3JkPTY1MTY1MWMxRjAyOCFAO011bHRpcGxlQWN0aXZlUmVzdWx0U2V0cz10cnVl
  customer-service-connection-string: U2VydmVyPWlkZW50aXR5LWRhdGFiYXNlO0RhdGFiYXNlPVN0b3JlQXBwQ3VzdG9tZXJEQjtVc2VyIElkPXNhOyBQYXNzd29yZD02NTE2NTFjMUYwMjghQDtNdWx0aXBsZUFjdGl2ZVJlc3VsdFNldHM9dHJ1ZQ==
  # statistics-service-connection-string: U2VydmVyPWlkZW50aXR5LWRhdGFiYXNlO0RhdGFiYXNlPVN0b3JlQXBwU3RhdGlzdGljc0RCO1VzZXIgSWQ9c2E7IFBhc3N3b3JkPTY1MTY1MWMxRjAyOCFAO011bHRpcGxlQWN0aXZlUmVzdWx0U2V0cz10cnVl
  statistics-service-connection-string: cmVkaXM6NjM3OSxwYXNzd29yZD02NTE2NTFjMUYwMjghQA==
  order-service-connection-string: U2VydmVyPWlkZW50aXR5LWRhdGFiYXNlO0RhdGFiYXNlPVN0b3JlQXBwT3JkZXJzREI7VXNlciBJZD1zYTsgUGFzc3dvcmQ9NjUxNjUxYzFGMDI4IUA7TXVsdGlwbGVBY3RpdmVSZXN1bHRTZXRzPXRydWU=
  event-bus-erlang-cookie: UmFuZDBtUjRiYml0TXFDbzBrMWU=
  event-bus-password: cmFiYml0bXFQYXNzd29yZDEyIQ==
  massTransit-credentials-password: cmFiYml0bXFQYXNzd29yZDEyIQ==
